name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: download
      run: git clone https://github.com/llvm/llvm-project --depth=1 --branch llvmorg-14.0.3
    - name: configure
      run: |
        mkdir installed
        cmake -GNinja -S llvm-project/llvm -B build -DCMAKE_BUILD_TYPE=Release "-DLLVM_ENABLE_PROJECTS=clang;compiler-rt" "-DCMAKE_INSTALL_PREFIX=$pwd/installed"
    - name: build
      run: cmake --build build -j3
    - uses: actions/upload-artifact@v3
      with:
        name: llvm-binaries
        path: |
          build/bin
          build/lib
